To 0.5
supabase/pg_net pull request #65
Opened 2022-09-01 04:41 UTC by steve-chavez

Small improvements to make pg_net a bit more stable.

Closes https://github.com/supabase/pg_net/issues/61 and https://github.com/supabase/pg_net/issues/44.

Also reducing unnecessary work done by pg_net to address cases where there is high amount of requests - [ref(slack link)](https://supabase.slack.com/archives/C02FHG9QQAF/p1661469904514469)

2022-09-01 04:48 UTC, soedirgo submitted a review, later dismissed

2022-09-01 04:55 UTC, soedirgo commented
Btw `supabase_functions.hooks` has `_http_response_id_fkey` which depends on `net.http_request_queue_pkey`. Can that be handled in a migration?

2022-09-01 05:07 UTC, soedirgo commented
Some issues with the 0.4 -> 0.5 upgrade script:
- dropping pkey constraint
```
ERROR:  cannot drop constraint http_request_queue_pkey on table net.http_request_queue because other objects depend on it
DETAIL:  constraint _http_response_id_fkey on table net._http_response depends on index net.http_request_queue_pkey
constraint hooks_request_id_fkey on table supabase_functions.hooks depends on index net.http_request_queue_pkey
```
- `_check_worker_is_up` rename: return type should be `void` instead of `trigger` - might need to drop + create the function
- drop index
```
ERROR:  index "_http_response_created_idx" does not exist
```
- set unlogged
```
ERROR:  could not change table "http_request_queue" to unlogged because it references logged table "_http_response"
```
```
ERROR:  could not change table "http_request_queue" to unlogged because it references logged table "hooks"
```

2022-09-01 23:02 UTC, steve-chavez commented
> dropping pkey constraint

Current queue doesn't have a FK

https://github.com/supabase/pg_net/blob/deed7125e30c455eafd1b9a324a50c8e0fd2e961/sql/pg_net.sql#L42-L43

This was removed on https://github.com/supabase/pg_net/commit/8538d83f7e24b4a77d2e7618a22f2070499fe49a#diff-539e81249472b5ef91e28038ee011b645c8885f37ed6679e34d4483e23f4d390L46-R43

Already included on a previous script

https://github.com/supabase/pg_net/blob/deed7125e30c455eafd1b9a324a50c8e0fd2e961/sql/pg_net--0.2--0.3.sql#L7

How are you testing the upgrade script? I can't reproduce the error

2022-09-01 23:24 UTC, steve-chavez commented
> _check_worker_is_up rename: return type should be void instead of trigger - might need to drop + create the function

:white_check_mark: 

> drop index

Added IF EXISTS

> set unlogged

These now work.

2022-09-02 00:17 UTC, steve-chavez commented
I created a new supabase instance(has pg_net 0.2), enabled a webhook and did:

```sql
alter extension pg_net update to '0.3';
alter extension pg_net update to '0.4';
alter extension pg_net update to '0.5'; -- had to manually download pg_net--0.4--0.5.sql to /var/lib/postgresql/extension
```

And all of them ran successfully. Although I had to fix `pg_net--0.2--0.3.sql`(included on the latest commit).

2022-09-02 08:10 UTC, soedirgo requested changes
One more thing:

2022-09-02 08:10 UTC, soedirgo commented on sql/pg_net--0.2--0.3.sql
> +truncate net._http_response cascade;
This will truncate all user tables with a FK to these tables, which is not OK.

2022-09-02 09:13 UTC, soedirgo commented on sql/pg_net--0.2--0.3.sql
> +truncate net._http_response cascade;
Actually, removing `cascade` will make it fail if there are FKs to it. How about just moving the `truncate`s until after we drop the PK constraints?

2022-09-02 19:03 UTC, steve-chavez commented on sql/pg_net--0.2--0.3.sql
> +truncate net._http_response cascade;
How about just removing the TRUNCATE. I don't see why it's needed.

2022-09-03 06:35 UTC, soedirgo commented on sql/pg_net--0.2--0.3.sql
> +truncate net._http_response cascade;
Hmm yeah let's remove it.

2022-09-04 20:21 UTC, steve-chavez commented on sql/pg_net--0.2--0.3.sql
> +truncate net._http_response cascade;
Cool, done.

2022-09-05 06:33 UTC, soedirgo approved these changes

2022-09-05 13:30 UTC, merged